/* empty css                      */(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),s=l.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="31" height="31" viewBox="0 0 31 31" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M27.125 7.75V10.3333H3.875V7.75H27.125ZM3.875 23.25H27.125V20.6667H3.875V23.25ZM3.875 16.7917H27.125V14.2083H3.875V16.7917Z" fill="#010101" />
</svg>
    `,o=`
<svg width="34" height="34" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M28.3334 28.3334L5.66675 5.66669M28.3334 5.66669L5.66675 28.3334" stroke="black" stroke-opacity="0.8" stroke-width="3.41667" stroke-linecap="round" />
</svg>
    `;l.addEventListener("click",()=>{t=!t,s.innerHTML=t?o:c,t?n():r()}),a.forEach(d=>d.addEventListener("click",()=>{r(),s.innerHTML=c,t=!1})),window.addEventListener("scroll",i);function n(){u.style.display="block"}function r(){u.style.display="none"}function i(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function s(o){const n=document.getElementById(o);if(!n)return;const r=l(),i=n.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const r=this.getAttribute("href");if(!r)return;const[i,d]=r.split("#");if(!d)return;const f=window.location.pathname.split("/").pop();!(i===""||i==="./"||i===f||i==="./"+f)||!document.getElementById(d)||(n.preventDefault(),s(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(r=>r.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function c(){const o=window.pageYOffset+l()+100;a.forEach(n=>{const r=n.offsetTop,i=r+n.offsetHeight;o>=r&&o<i&&t(n.id)})}if(window.addEventListener("scroll",c),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{s(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
